NANOSECONDS = 1
MICROSECONDS = NANOSECONDS * 1000
MILLISECONDS = MICROSECONDS *1000
SECONDS = MILLISECONDS *1000

MINE_RATE = SECONDS * 4

STARTING_BALANCE = 1000

MINING_REWARD = 50

MINING_REWARD_INPUT= {'address' :'**--RewardMiner--**'}